version: 1.2

workflows:
  - name: sfkit
    subclass: WDL
    primaryDescriptorPath: /workflow.wdl
    publish: true
    filters:
      branches:
        - main
    authors:
      - orcid: 0009-0006-6451-8062 # Denis Loginov
      - name: Simon Mendelsohn
        email: smendels@broadinstitute.org
      - orcid: 0000-0002-2713-0150 # Hyunghoon Cho

  - name: sfkit-dev
    subclass: WDL
    primaryDescriptorPath: /workflow.wdl
    publish: true
