import sys

import nacl.secret
import nacl.utils
from nacl.encoding import HexEncoder
from nacl.public import Box, PrivateKey, PublicKey
from tqdm import tqdm

from random_number_generator import RandomNumberGenerator


def add_others_r(file, rng, others_num_inds, mode):
    """
    Adds the pseudo-random number generated by the other user to the file.
    """
    input_file = open(f"input_data/{file}", "r")
    num_columns = len(input_file.readline().split("\t"))
    if debug:
        print("Columns: ", num_columns)
    output_file = open(f"output_data/{file}", mode)
    print(f"Adding random numbers to output_data/{file}...")
    for _ in tqdm(range(others_num_inds)):
        for j in range(num_columns):
            output_file.write(str(rng.next()) + " ")
        output_file.write("\n")


def encrypt(file, rng, mode):
    """
    Encrypts the given file using the given random number generator in a manner
    that is compatible with the secret-sharing scheme used in our GWAS protocol.
    """
    input_file = open(f"input_data/{file}", "r")
    output_file = open(f"output_data/{file}", mode)
    file_lines = input_file.readlines()
    print(f"Encrypting input_data/{file}...")
    for line in tqdm(file_lines):
        line = line.strip()
        line = line.split("\t")
        for genotype in line:
            output_file.write(str(int(genotype) - rng.next()) + " ")
        output_file.write("\n")


def get_shared_keys(my_private_key, other_public_key):
    """
    Given the private key of the user and the public key of the other user, generate 2 shared keys.
    The first is for the user with role 1 and the second is for the user with role 2.
    """
    shared_key_prototype = Box(my_private_key, other_public_key)
    box = nacl.secret.SecretBox(shared_key_prototype.shared_key())
    nonce = 1
    nacl.utils.random(nacl.secret.SecretBox.NONCE_SIZE)
    shared_key_1 = box.encrypt(
        b"Hello to you !!!", nonce=nonce.to_bytes(24, byteorder="big")
    ).ciphertext
    nonce += 1
    shared_key_2 = box.encrypt(
        b"Hello to you !!!", nonce=nonce.to_bytes(24, byteorder="big")
    ).ciphertext

    if debug:
        print("Role 1's Key:", shared_key_1)
        print("Role 2's Key:", shared_key_2)

    return [None, shared_key_1, shared_key_2]


def get_users_input():
    if debug:
        role = 1
        other_num_inds = 10
        my_private_key = PrivateKey(
            "134197d25ddd95dda789fddbbd9f3329bab3ed5fe31a3b184cf40d780dd206e7",
            encoder=HexEncoder,
        )
        other_public_key = PublicKey(
            "b6abeabb695a23e76315ded61f9ba750f57c79b6eaa4ab0fc28ade4df8517a06",
            encoder=HexEncoder,
        )
    else:
        # get user's role
        role = int(input("Please enter your role (1 or 2): "))
        if role not in [1, 2]:
            print("Invalid role; role must be 1 or 2.  Exiting.")
            sys.exit(1)
        # get the number of individuals in the other user's dataset
        other_num_inds = int(
            input(
                "Please enter the number of individuals in the other user's dataset: "
            )
        )
        # read in the keys
        my_private_key = PrivateKey(
            input("Enter your private key: "), encoder=HexEncoder
        )
        other_public_key = PublicKey(
            input("Enter the other participant's public key: "), encoder=HexEncoder
        )

    return (role, other_num_inds, my_private_key, other_public_key)


def main():
    (role, others_num_inds, my_private_key, other_public_key) = get_users_input()

    shared_keys = get_shared_keys(my_private_key, other_public_key)

    rng1, rng2 = (
        RandomNumberGenerator(shared_keys[1]),
        RandomNumberGenerator(shared_keys[2]),
    )

    # encrypt the data
    files = ["cov.txt", "pheno.txt", "geno.txt"]
    if role == 1:
        for file in files:
            encrypt(file, rng1, "w")
            add_others_r(file, rng2, others_num_inds, "a")
    elif role == 2:
        for file in files:
            add_others_r(file, rng1, others_num_inds, "w")
            encrypt(file, rng2, "a")

    print("\n\nThe encryption is complete. Please upload output_data to Google Cloud.")


if __name__ == "__main__":
    global debug
    debug = False
    if len(sys.argv) > 1 and sys.argv[1] == "debug":
        debug = True
    main()
